services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nefertum-nest:dev
    container_name: nefertum-api
    working_dir: /app
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - nefertum-nest-node-modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: nefertum-postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - nefertum-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: nefertum-nest:dev
    container_name: nefertum-migrate
    working_dir: /app
    command: npx prisma migrate dev
    env_file:
      - .env.docker
    profiles:
      - migrate
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  nefertum-pg-data:
  nefertum-nest-node-modules:
